import type { IntegrationTool } from "./types";

export const integrationCatalog: IntegrationTool[] = [
  {
    id: "checkov",
    name: "Checkov",
    vendor: "Bridgecrew / Prisma Cloud",
    category: "iac",
    description: "Static analysis for Terraform, CloudFormation, Kubernetes, ARM, and more.",
    ingest: ["sarif", "json", "cli"],
    status: "connected",
    docsUrl: "https://www.checkov.io/",
  },
  {
    id: "tfsec",
    name: "tfsec",
    vendor: "Aqua Security",
    category: "iac",
    description: "Security scanner for Terraform with rich rule sets and inline ignores.",
    ingest: ["sarif", "json", "cli"],
    status: "available",
    docsUrl: "https://aquasecurity.github.io/tfsec/",
  },
  {
    id: "trivy",
    name: "Trivy",
    vendor: "Aqua Security",
    category: "iac",
    description: "Misconfigurations, vulnerabilities, and secrets across IaC, containers, and repos.",
    ingest: ["sarif", "json", "cli"],
    status: "connected",
    docsUrl: "https://trivy.dev/",
  },
  {
    id: "kics",
    name: "KICS",
    vendor: "Checkmarx",
    category: "iac",
    description: "Keeping Infrastructure as Code Secure — multi-IaC static analysis.",
    ingest: ["sarif", "json", "cli"],
    status: "available",
    docsUrl: "https://kics.io/",
  },
  {
    id: "terrascan",
    name: "Terrascan",
    vendor: "Tenable",
    category: "iac",
    description: "Policy-as-code scanner for cloud native infrastructure.",
    ingest: ["sarif", "json", "cli"],
    status: "available",
    docsUrl: "https://runterrascan.io/",
  },
  {
    id: "semgrep",
    name: "Semgrep",
    vendor: "Semgrep",
    category: "sast",
    description: "Fast static analysis with community and custom rules; CI-native.",
    ingest: ["sarif", "json", "cli"],
    status: "connected",
    docsUrl: "https://semgrep.dev/",
  },
  {
    id: "codeql",
    name: "CodeQL",
    vendor: "GitHub",
    category: "sast",
    description: "Semantic code analysis with variant analysis and GitHub Advanced Security.",
    ingest: ["sarif", "api"],
    status: "available",
    docsUrl: "https://codeql.github.com/",
  },
  {
    id: "sonarqube",
    name: "SonarQube / SonarCloud",
    vendor: "Sonar",
    category: "sast",
    description: "Continuous inspection of code quality and security hotspots.",
    ingest: ["api", "webhook"],
    status: "available",
    docsUrl: "https://www.sonarsource.com/",
  },
  {
    id: "bandit",
    name: "Bandit",
    vendor: "PyCQA",
    category: "sast",
    description: "Python security linter focused on common vulnerability classes.",
    ingest: ["json", "sarif", "cli"],
    status: "planned",
    docsUrl: "https://bandit.readthedocs.io/",
  },
  {
    id: "gosec",
    name: "Gosec",
    vendor: "SecureGo",
    category: "sast",
    description: "Go security checker for common Go vulnerability patterns.",
    ingest: ["json", "sarif", "cli"],
    status: "planned",
    docsUrl: "https://github.com/securego/gosec",
  },
  {
    id: "zap",
    name: "OWASP ZAP",
    vendor: "OWASP",
    category: "dast",
    description: "World-class dynamic app security testing with automation framework.",
    ingest: ["api", "json", "sarif"],
    status: "connected",
    docsUrl: "https://www.zaproxy.org/",
  },
  {
    id: "nuclei",
    name: "Nuclei",
    vendor: "ProjectDiscovery",
    category: "dast",
    description: "Template-based vulnerability scanner for web and infra.",
    ingest: ["json", "sarif", "cli"],
    status: "available",
    docsUrl: "https://github.com/projectdiscovery/nuclei",
  },
  {
    id: "burp",
    name: "Burp Suite Enterprise",
    vendor: "PortSwigger",
    category: "dast",
    description: "Enterprise DAST with REST API and CI-driven scans.",
    ingest: ["api", "json"],
    status: "planned",
    docsUrl: "https://portswigger.net/burp",
  },
  {
    id: "stackhawk",
    name: "StackHawk",
    vendor: "StackHawk",
    category: "dast",
    description: "Developer-first DAST in CI with OpenAPI-aware testing.",
    ingest: ["api", "sarif", "cli"],
    status: "available",
    docsUrl: "https://www.stackhawk.com/",
  },
  {
    id: "snyk-sca",
    name: "Snyk Open Source",
    vendor: "Snyk",
    category: "sca",
    description: "Dependency vulnerability and license posture with fix guidance.",
    ingest: ["api", "sarif", "json"],
    status: "connected",
    docsUrl: "https://snyk.io/",
  },
  {
    id: "osv",
    name: "OSV Scanner",
    vendor: "Google / OSV",
    category: "sca",
    description: "Lightweight scanner against the Open Source Vulnerabilities database.",
    ingest: ["json", "sarif", "cli"],
    status: "available",
    docsUrl: "https://google.github.io/osv-scanner/",
  },
  {
    id: "grype",
    name: "Grype",
    vendor: "Anchore",
    category: "sca",
    description: "SBOM and image vulnerability scanning with CycloneDX/Syft ecosystem.",
    ingest: ["json", "sarif", "cli"],
    status: "available",
    docsUrl: "https://github.com/anchore/grype",
  },
  {
    id: "dependabot",
    name: "Dependabot",
    vendor: "GitHub",
    category: "sca",
    description: "Automated dependency updates and security PRs in GitHub.",
    ingest: ["api", "webhook"],
    status: "connected",
    docsUrl: "https://github.com/dependabot",
  },
  {
    id: "trufflehog",
    name: "TruffleHog",
    vendor: "Truffle Security",
    category: "secrets",
    description: "Secret scanning across git history, CI, and filesystem with verified detectors.",
    ingest: ["json", "sarif", "cli"],
    status: "connected",
    docsUrl: "https://trufflesecurity.com/",
  },
  {
    id: "gitleaks",
    name: "Gitleaks",
    vendor: "Gitleaks",
    category: "secrets",
    description: "Fast secret scanning for repos and CI with allowlists.",
    ingest: ["json", "sarif", "cli"],
    status: "available",
    docsUrl: "https://gitleaks.io/",
  },
  {
    id: "gitguardian",
    name: "GitGuardian",
    vendor: "GitGuardian",
    category: "secrets",
    description: "Secrets detection, Honeytokens, and posture for org-wide Git.",
    ingest: ["api", "webhook"],
    status: "planned",
    docsUrl: "https://www.gitguardian.com/",
  },
  {
    id: "github-advanced-security",
    name: "GitHub Secret Scanning",
    vendor: "GitHub",
    category: "secrets",
    description: "Native push protection and partner pattern alerts.",
    ingest: ["api", "webhook"],
    status: "connected",
    docsUrl: "https://docs.github.com/en/code-security",
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    vendor: "GitHub",
    category: "cicd",
    description: "Workflow telemetry, required checks, and OIDC hardening.",
    ingest: ["webhook", "api"],
    status: "connected",
    docsUrl: "https://docs.github.com/en/actions",
  },
  {
    id: "gitlab-ci",
    name: "GitLab CI",
    vendor: "GitLab",
    category: "cicd",
    description: "Pipelines, security dashboards, and compliance frameworks.",
    ingest: ["api", "webhook"],
    status: "available",
    docsUrl: "https://docs.gitlab.com/ee/ci/",
  },
  {
    id: "azure-devops",
    name: "Azure DevOps Pipelines",
    vendor: "Microsoft",
    category: "cicd",
    description: "YAML pipelines with Azure Key Vault and Defender for DevOps.",
    ingest: ["api", "webhook"],
    status: "available",
    docsUrl: "https://azure.microsoft.com/en-us/products/devops",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    vendor: "CDF",
    category: "cicd",
    description: "Plugin ecosystem for security gates and artifact promotion.",
    ingest: ["webhook", "api"],
    status: "planned",
    docsUrl: "https://www.jenkins.io/",
  },
  {
    id: "kyverno",
    name: "Kyverno",
    vendor: "Kyverno",
    category: "k8s",
    description: "Kubernetes-native policy engine for admission and CI validation.",
    ingest: ["json", "cli"],
    status: "available",
    docsUrl: "https://kyverno.io/",
  },
  {
    id: "falco",
    name: "Falco",
    vendor: "Falco",
    category: "k8s",
    description: "Runtime threat detection for Linux and Kubernetes workloads.",
    ingest: ["api", "json"],
    status: "planned",
    docsUrl: "https://falco.org/",
  },
];
